name: moleculer

services:
  node1:
    image: debdutdeb/moleculer-experiment:1

    environment:
      PORT: ${PORT}
      TCP_PORT: ${TCP_PORT}
      INSTANCE_IP: ${INSTANCE_IP}

    ports:
      - ${PORT}:${PORT}
      - ${TCP_PORT}:${TCP_PORT}

    volumes:
      - ./instances.db:/app/instances.db
